[package]
name = "gkr"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bn254 = "0.5.0"
ark-ff = "0.5.0"
multivariate_poly = {path = "../multivariate_poly"}
univariate_poly = {path = "../univariate_poly"}
sha3 = "0.10.8"
sum_check = {path = "../sum_check"}
