[package]
name = "shamir_secret_sharing"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bn254 = "0.5.0"
ark-ff = "0.5.0"
ark-std = "0.5.0"
lagrange_impl = {path = "../lagrange_impl"}
rand = "0.8.5"
