[package]
name = "shamir_secret_sharing"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bn254 = "0.5.0"
ark-ff = "0.5.0"
ark-std = "0.5.0"
univariate_poly = {path = "../univariate_poly"}
rand = "0.8.5"
